spring:
  profiles:
  active:
  - dev

---
spring:
  profiles: dev
  application:
    name:microservicecloud-config-shitj-dev

--
spring:
  profiles: test
  application:
    name: microservicecloud-config-shitj-test
